data=File.new(ARGV[0]).read().force_encoding('utf-8')
style=Regexp.new('^Style:\s+[^,]+,([^,]+),')
script=Regexp.new('{\\\\fn([^}\\\\]+)[^}]*}')
f1=data.scan(style).flatten.uniq.join("\n")
f2=data.scan(script).flatten.uniq.join("\n")
File.new(ARGV[0]+"_font.txt",'w').write(f1+"\n"+f2)
